### ISSUE TITLE
Problem running the Monadic version of randString

### ISSUE THREAD

**Issue by matmsh** [noelmarkham/lambdadays-2015#3]
Hi,
  I have a compliation error when trying to run the monadic version of randString  in
WritingTest.scala. 
More specifically, I get the following compilation error on the piece of code below. 

[error]  --- because ---
[error] argument expression's type is not compatible with formal parameter type;
[error]  found   : String => scalaz.ReaderT[scala.concurrent.Future,com.noelmarkham.scaladays.external.Config,List[com.noelmarkham.scaladays.external.Twitter.Tweet]]
[error]  required: String => ?M
[error]     val resultT = randString(getTweets _, generateString _)("noelmarkham")
[error]                   ^
[error] one error found

 def runReaderM(): Unit = {
    import scalaz.Kleisli._

```
def randString[M[_] : Monad](getTweetsF: String => M[List[Twitter.Tweet]],
                             generateTextF: String => M[String]
                              )(username: String): M[String] = {
  for {
    tweets <- getTweetsF(username)
    tweetsAsText = tweets.map(_.content).mkString(" ")
    randomString <- generateTextF(tweetsAsText)
  } yield randomString
}

def getTweets(username: String): ReaderT[Future, Config,List[Twitter.Tweet]] = {
  kleisli { c =>
    Twitter.getTweets(username, c.key, c.secret)
  }
}

def generateString(text: String): ReaderT[Future, Config, String] = {
  kleisli { c =>
    Markov.generateString(text, c.context)
  }
}


// compilation error
val resultT = randString(getTweets _, generateString _)("noelmarkham")

val resultFuture: Future[String] = resultT.run(Config("a", "b", 2))
val result = Await.result(resultFuture, 2 seconds)
println(result)
```

  }

It would be very much appreciated it if you could point out what I have done wrong.

Thanks in advance for your assistance !
Shing

**Comment by matmsh** [comment]
I have managed to fix the compilation with the following. 

```
 type MM[A] = ReaderT[Future, Config, A]

 def getTweets(username: String): MM[List[Twitter.Tweet]] = {
      kleisli { c =>
        Twitter.getTweets(username, c.key, c.secret)
      }
    }

def generateString(text: String): MM[String] = {
      kleisli { (c: Config) => Markov.generateString(text, c.context) }
    }


```

I am not sure the above is the best solution. 

Shing

**Comment by noelmarkham** [comment]
Hi,

First, I'm so so sorry I've taken so long to reply to this - I seem to have missed your request first time around.

Looking at the signatures:

``` scala
def getTweets(username: String):
      ReaderT[Future, Config, List[Tweet]] = {
  kleisli { c =>
   Twitter.getTweets(username, c.key, c.secret)
  }
}
```

and 

``` scala
def generateString(text: String):
      ReaderT[Future, Config, String] = {
  kleisli { c =>
    Markov.generateString(text, c.context)
  }
}
```

You can see that they're both `String => ReaderT[Future, Config, X]`
but the functions are expecting `String => M[X]`, not specifically `ReaderT`:

``` scala
def randString[M[_]: Monad](
    getTweetsF: String => M[List[Tweet]],
    generateTextF: String => M[String]
  )(username: String): M[String]
```

However, as I point out, `ReaderT`s are monads, so what's the problem here? Exactly as you described, you need to tell the Scala compiler to fill in the missing "holes" in the type constructor.

So yes, your approach is exactly right, in that you need to fill int the holes to make a `ReaderT` - which takes three type holes into a monad, which only has one. It is possible to do this inline, but the syntax is horrible:

``` scala
scala> val resultT = randString[({type λ[α] = ReaderT[Future, Config, α]})#λ](getTweets _, generateString _)("noelmarkham")
resultT: scalaz.Kleisli[scala.concurrent.Future,Config,String] = Kleisli(<function1>)
```

Note that it's convention to use Greek symbols here, you can use anything. Also, take a look at the [Kind Projector](https://github.com/non/kind-projector), which is part of the typelevel fork (and I think a plugin too), which makes these type lambdas much nicer to work with.

I hope this helps.

**Comment by matmsh** [comment]
Thanks for the reply !
Shing
